#!/usr/bin/env python



import sys



pitch = {
  'C' : -9,
  'D' : -7,
  'E' : -5,
  'F' : -4,
  'G' : -2,
  'A' : +0,
  'B' : +2
}



def tone(note):
  return pitch[note[0]] + sum([-1 if x == 'b' else +1 for x in note[1:]])



def main(argv):
  if len(argv) not in (2, 3):
    print('%s [A-G][b|#]* [octave=4]' % argv[0])
  else:
    print(440 * 2 ** ((int(argv[2]) - 4 if len(argv) == 3 else 0) + (tone(argv[1]) / 12.0)))



if __name__ == '__main__':
  main(sys.argv)
